name: Github-Actions

on: [push, pull_request]

jobs:
  vagrant-validation:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install packer
      run: ./generic-ci.sh install-packer

    - name: verify local.json
      run: ./generic-ci.sh verify-local

    - name: verify vagrant.json
      run: ./generic-ci.sh verify-official

    - name: verify cloud.json
      run: ./generic-ci.sh verify-cloud

  python-syntax-validation:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install flake8
      run: ./generic-ci.sh install-flake8

    - name: run flake8 checks
      run: ./generic-ci.sh flake8

  python-format-validation:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install yapf
      run: ./generic-ci.sh install-yapf

    - name: run yapf checks
      run: ./generic-ci.sh yapf

  shell-syntax-validation:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: run shellcheck
      run: ./generic-ci.sh shellcheck

  shell-format-validation:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install-shfmt
      run: ./generic-ci.sh install-shfmt

    - name: run shfmt checks
      run: ./generic-ci.sh shfmt
